parser: babel-eslint

parserOptions:
  ecmaFeatures:
    jsx: true

plugins:
  - prettier
  - import

env:
  browser: true
  node: true
  es6: true

rules:
  # prettier rules
  prettier/prettier:
    - 2
    -
      trailingComma: es5
      singleQuote: true
      semi: true

  # eslint rules
  prefer-const: 2
  no-unused-vars: 
    - 2
    -
      argsIgnorePattern: ^_
      varsIgnorePattern: ^_
  no-multiple-empty-lines:
    - 2
    - max: 1
  
  # import rules
  import/newline-after-import: 2
  import/imports-first: 2
  import/no-dynamic-require: 2
  import/no-extraneous-dependencies: 2
  import/no-mutable-exports: 2
  import/no-commonjs: 2

